### PR TITLE
Contract Update: marketpools fee

### PR DESCRIPTION
**Pull request by donchate**
Addition of a **0.25% fee** for swapping tokens. The fee is immediately deposited to liquidity reserves and increases the proportional value of all liquidity provider shares. LPs realize the gain when removing liquidity.

### CODE REVIEW

**Review by bt-cryptomancer — CHANGES_REQUESTED** [review]
Can you make the fee percentage configurable in the params table?  That way we can easily change it later on if desired, without having to do a contract update.

**Comment by reazuliqbal** [comment]
Hi, is it possible to emit the fee charged as transaction event? It would be very helpful while doing calculation for tax purpose.

**Comment by donchate** [comment]
Moved fee to params and added fee to emit.

**Review by bt-cryptomancer — APPROVED** [review]
Changes look good.

**Pull request merged**
