### PR TITLE
Crash debug logging using loglevel library

### PR DESCRIPTION
**Pull request by eonwarped**
Added config parameter to tweak log level to help in crash scenarios.

### CODE REVIEW

**Review by bt-cryptomancer — CHANGES_REQUESTED** [review]
The actual code changes look good, however I noticed you updated the package-lock.json file to use lockfileVersion 2.  I believe this version 2 format requires a newer version of npm.  Introducing the loglevel library shouldn't change the minimum version of npm required to run the node, right? So to avoid affecting compatibility with older versions of npm, I'd prefer to have package-lock.json reverted back to the previous lockfileVersion 1 format.  Unless you feel strongly about having it be lockfileVersion 2 for some reason.

**Comment by 4Ykw** [comment]
Tested myself these for already 2 weeks at least. So far no issues.

**Comment by eonwarped** [comment]
Yeah, I think it just automatically updated the lockfile version when I did npm install . Don't think it changes node version compatibility. I think it's fine to just have people use the newer version of npm.

**Review by bt-cryptomancer — APPROVED** [review]
Okay, I did a bit of reading about lockfileVersion 2 and noticed that it is backwards compatible with npm 6.  I guess it doesn't really matter which version we use, and the underlying Node.js compatibility doesn't change either.  So if you guys have no concerns about it, then I'm fine with it too.

Happy to approve this PR now.

**Pull request merged**
